/*
 * Tests generated by AI.
 */

#include <stddef.h>

#define VECTOR_IMPL_CENTRY
#include "../vector.h"

#include "./lib/greatest.h"

typedef struct {
    int id;
    double score;
} record;

TEST init_creates_empty_vector(void)
{
    int *v = NULL;
    vec_init(v, int);
    ASSERT(v != NULL);
    ASSERT_EQ_FMT((size_t)0, vec_size(v), "%zu");
    ASSERT(vec_capacity(v) >= vec_size(v));
    vec_free(v);
    PASS();
}

TEST init_records_element_size(void)
{
    int *vi = NULL;
    vec_init(vi, int);
    double *vd = NULL;
    vec_init(vd, double);
    record *vr = NULL;
    vec_init(vr, record);

    ASSERT_EQ_FMT(sizeof(int), vec_type_size(vi), "%zu");
    ASSERT_EQ_FMT(sizeof(double), vec_type_size(vd), "%zu");
    ASSERT_EQ_FMT(sizeof(record), vec_type_size(vr), "%zu");

    vec_free(vi);
    vec_free(vd);
    vec_free(vr);
    PASS();
}

TEST free_resets_pointer_to_null(void)
{
    int *v = NULL;
    vec_init(v, int);
    vec_push_back(v, 1);
    vec_free(v);
    ASSERT(v == NULL);
    PASS();
}

TEST free_twice_is_safe(void)
{
    int *v = NULL;
    vec_init(v, int);
    vec_push_back(v, 7);

    vec_free(v);
    ASSERT(v == NULL);
    vec_free(v);
    ASSERT(v == NULL);
    PASS();
}

TEST push_back_appends_and_grows_size(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 5; i++) {
        vec_push_back(v, i * 10);
        ASSERT_EQ_FMT((size_t)(i + 1), vec_size(v), "%zu");
    }
    for (int i = 0; i < 5; i++) {
        ASSERT_EQ_FMT(i * 10, v[i], "%d");
    }
    ASSERT(vec_capacity(v) >= vec_size(v));
    vec_free(v);
    PASS();
}

TEST capacity_never_below_size(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 64; i++) {
        vec_push_back(v, i);
        ASSERT(vec_capacity(v) >= vec_size(v));
    }
    vec_free(v);
    PASS();
}

TEST pop_back_removes_last_and_keeps_prefix(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 4; i++)
        vec_push_back(v, i);

    vec_pop_back(v);
    ASSERT_EQ_FMT((size_t)3, vec_size(v), "%zu");
    for (int i = 0; i < 3; i++)
        ASSERT_EQ_FMT(i, v[i], "%d");

    vec_free(v);
    PASS();
}

TEST pop_back_on_empty_is_noop(void)
{
    int *v = NULL;
    vec_init(v, int);

    vec_pop_back(v);
    ASSERT_EQ_FMT((size_t)0, vec_size(v), "%zu");

    vec_push_back(v, 5);
    ASSERT_EQ_FMT((size_t)1, vec_size(v), "%zu");
    ASSERT_EQ_FMT(5, v[0], "%d");

    vec_free(v);
    PASS();
}

TEST insert_at_front_shifts_right(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 1; i <= 3; i++)
        vec_push_back(v, i);

    vec_insert(v, 0, 99);
    ASSERT_EQ_FMT((size_t)4, vec_size(v), "%zu");
    int expect[4] = {99, 1, 2, 3};
    for (int i = 0; i < 4; i++)
        ASSERT_EQ_FMT(expect[i], v[i], "%d");

    vec_free(v);
    PASS();
}

TEST insert_in_middle_shifts_right(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 4; i++)
        vec_push_back(v, i);

    vec_insert(v, 2, 77);
    ASSERT_EQ_FMT((size_t)5, vec_size(v), "%zu");
    int expect[5] = {0, 1, 77, 2, 3};
    for (int i = 0; i < 5; i++)
        ASSERT_EQ_FMT(expect[i], v[i], "%d");

    vec_free(v);
    PASS();
}

TEST insert_at_end_is_append(void)
{
    int *v = NULL;
    vec_init(v, int);
    vec_push_back(v, 1);
    vec_push_back(v, 2);

    vec_insert(v, vec_size(v), 3);
    ASSERT_EQ_FMT((size_t)3, vec_size(v), "%zu");
    ASSERT_EQ_FMT(3, v[2], "%d");

    vec_free(v);
    PASS();
}

TEST insert_into_empty_vector(void)
{
    int *v = NULL;
    vec_init(v, int);

    vec_insert(v, 0, 42);
    ASSERT_EQ_FMT((size_t)1, vec_size(v), "%zu");
    ASSERT_EQ_FMT(42, v[0], "%d");

    vec_free(v);
    PASS();
}

TEST insert_triggers_realloc(void)
{
    int *v = NULL;
    vec_init(v, int);

    size_t cap0 = vec_capacity(v);
    for (size_t i = 0; i < cap0; i++)
        vec_push_back(v, (int)i);
    ASSERT_EQ_FMT(cap0, vec_size(v), "%zu");

    vec_insert(v, 0, -1);
    ASSERT(vec_capacity(v) > cap0);
    ASSERT_EQ_FMT(cap0 + 1, vec_size(v), "%zu");
    ASSERT_EQ_FMT(-1, v[0], "%d");
    for (size_t i = 0; i < cap0; i++)
        ASSERT_EQ_FMT((int)i, v[i + 1], "%d");

    vec_free(v);
    PASS();
}

TEST erase_front_shifts_left(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 4; i++)
        vec_push_back(v, i);

    vec_erase(v, 0);
    ASSERT_EQ_FMT((size_t)3, vec_size(v), "%zu");
    int expect[3] = {1, 2, 3};
    for (int i = 0; i < 3; i++)
        ASSERT_EQ_FMT(expect[i], v[i], "%d");

    vec_free(v);
    PASS();
}

TEST erase_middle_shifts_left(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 5; i++)
        vec_push_back(v, i);

    vec_erase(v, 2);
    ASSERT_EQ_FMT((size_t)4, vec_size(v), "%zu");
    int expect[4] = {0, 1, 3, 4};
    for (int i = 0; i < 4; i++)
        ASSERT_EQ_FMT(expect[i], v[i], "%d");

    vec_free(v);
    PASS();
}

TEST erase_last_element(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 3; i++)
        vec_push_back(v, i);

    vec_erase(v, vec_size(v) - 1);
    ASSERT_EQ_FMT((size_t)2, vec_size(v), "%zu");
    ASSERT_EQ_FMT(0, v[0], "%d");
    ASSERT_EQ_FMT(1, v[1], "%d");

    vec_free(v);
    PASS();
}

TEST erase_out_of_bounds_is_noop(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 3; i++)
        vec_push_back(v, i);

    vec_erase(v, 99);
    ASSERT_EQ_FMT((size_t)3, vec_size(v), "%zu");
    for (int i = 0; i < 3; i++)
        ASSERT_EQ_FMT(i, v[i], "%d");

    vec_erase(v, vec_size(v));
    ASSERT_EQ_FMT((size_t)3, vec_size(v), "%zu");
    for (int i = 0; i < 3; i++)
        ASSERT_EQ_FMT(i, v[i], "%d");

    vec_free(v);
    PASS();
}

TEST clear_sets_size_to_zero(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 6; i++)
        vec_push_back(v, i);

    vec_clear(v);
    ASSERT_EQ_FMT((size_t)0, vec_size(v), "%zu");

    vec_free(v);
    PASS();
}

TEST clear_keeps_vector_reusable(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 6; i++)
        vec_push_back(v, i);

    vec_clear(v);
    vec_push_back(v, 42);
    ASSERT_EQ_FMT((size_t)1, vec_size(v), "%zu");
    ASSERT_EQ_FMT(42, v[0], "%d");

    vec_free(v);
    PASS();
}

TEST clear_retains_capacity(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 8; i++)
        vec_push_back(v, i);

    size_t cap_before = vec_capacity(v);
    vec_clear(v);
    ASSERT_EQ_FMT(cap_before, vec_capacity(v), "%zu");

    vec_free(v);
    PASS();
}

TEST resize_grow_keeps_prefix_and_zeroes_tail(void)
{
    int *v = NULL;
    vec_init(v, int);
    vec_push_back(v, 1);
    vec_push_back(v, 2);

    vec_resize(v, 5);
    ASSERT_EQ_FMT((size_t)5, vec_size(v), "%zu");
    ASSERT(vec_capacity(v) >= vec_size(v));
    ASSERT_EQ_FMT(1, v[0], "%d");
    ASSERT_EQ_FMT(2, v[1], "%d");
    for (int i = 2; i < 5; i++)
        ASSERT_EQ_FMT(0, v[i], "%d");

    vec_free(v);
    PASS();
}

TEST resize_shrink_updates_size_and_keeps_prefix(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 6; i++)
        vec_push_back(v, i);

    vec_resize(v, 3);
    ASSERT_EQ_FMT((size_t)3, vec_size(v), "%zu");
    for (int i = 0; i < 3; i++)
        ASSERT_EQ_FMT(i, v[i], "%d");

    vec_free(v);
    PASS();
}

TEST resize_to_zero_empties_vector(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 4; i++)
        vec_push_back(v, i);

    vec_resize(v, 0);
    ASSERT_EQ_FMT((size_t)0, vec_size(v), "%zu");

    vec_free(v);
    PASS();
}

TEST resize_regrow_after_shrink_zeroes(void)
{
    int *v = NULL;
    vec_init(v, int);
    for (int i = 0; i < 6; i++)
        vec_push_back(v, i + 1);

    vec_resize(v, 2);
    ASSERT_EQ_FMT((size_t)2, vec_size(v), "%zu");

    vec_resize(v, 5);
    ASSERT_EQ_FMT((size_t)5, vec_size(v), "%zu");
    ASSERT_EQ_FMT(1, v[0], "%d");
    ASSERT_EQ_FMT(2, v[1], "%d");
    for (int i = 2; i < 5; i++)
        ASSERT_EQ_FMT(0, v[i], "%d");

    vec_free(v);
    PASS();
}

TEST swap_exchanges_size_and_contents(void)
{
    int *a = NULL;
    vec_init(a, int);
    int *b = NULL;
    vec_init(b, int);
    for (int i = 0; i < 3; i++)
        vec_push_back(a, i);
    for (int i = 0; i < 2; i++)
        vec_push_back(b, 100 + i);

    vec_swap(a, b);

    ASSERT_EQ_FMT((size_t)2, vec_size(a), "%zu");
    ASSERT_EQ_FMT((size_t)3, vec_size(b), "%zu");
    ASSERT_EQ_FMT(100, a[0], "%d");
    ASSERT_EQ_FMT(101, a[1], "%d");
    int expect_b[3] = {0, 1, 2};
    for (int i = 0; i < 3; i++)
        ASSERT_EQ_FMT(expect_b[i], b[i], "%d");

    vec_free(a);
    vec_free(b);
    PASS();
}

TEST swap_with_empty_vector(void)
{
    int *a = NULL;
    vec_init(a, int);
    int *b = NULL;
    vec_init(b, int);
    for (int i = 0; i < 3; i++)
        vec_push_back(a, i);

    vec_swap(a, b);

    ASSERT_EQ_FMT((size_t)0, vec_size(a), "%zu");
    ASSERT_EQ_FMT((size_t)3, vec_size(b), "%zu");
    for (int i = 0; i < 3; i++)
        ASSERT_EQ_FMT(i, b[i], "%d");

    vec_free(a);
    vec_free(b);
    PASS();
}

TEST stores_struct_elements_by_value(void)
{
    record *v = NULL;
    vec_init(v, record);
    ASSERT_EQ_FMT(sizeof(record), vec_type_size(v), "%zu");

    record r0 = {1, 1.5};
    record r1 = {2, 2.5};
    vec_push_back(v, r0);
    vec_push_back(v, r1);

    ASSERT_EQ_FMT((size_t)2, vec_size(v), "%zu");
    ASSERT_EQ_FMT(1, v[0].id, "%d");
    ASSERT_EQ_FMT(2, v[1].id, "%d");
    ASSERT_IN_RANGE(1.5, v[0].score, 1e-9);
    ASSERT_IN_RANGE(2.5, v[1].score, 1e-9);

    vec_free(v);
    PASS();
}

TEST stores_many_struct_elements(void)
{
    record *v = NULL;
    vec_init(v, record);

    enum { N = 5000 };
    for (int i = 0; i < N; i++) {
        record r = {i, i * 0.5};
        vec_push_back(v, r);
    }
    ASSERT_EQ_FMT((size_t)N, vec_size(v), "%zu");

    for (int i = 0; i < N; i++) {
        if (v[i].id != i)
            FAILm("struct id corrupted across reallocations");
        ASSERT_IN_RANGE(i * 0.5, v[i].score, 1e-9);
    }
    ASSERT(vec_capacity(v) >= vec_size(v));

    vec_free(v);
    PASS();
}

TEST stress_many_push_then_pop(void)
{
    int *v = NULL;
    vec_init(v, int);

    enum { N = 10000 };
    for (int i = 0; i < N; i++)
        vec_push_back(v, i);
    ASSERT_EQ_FMT((size_t)N, vec_size(v), "%zu");

    for (int i = 0; i < N; i++) {
        if (v[i] != i)
            FAILm("element corrupted across reallocations");
    }
    ASSERT(vec_capacity(v) >= vec_size(v));

    for (int i = 0; i < N; i++)
        vec_pop_back(v);
    ASSERT_EQ_FMT((size_t)0, vec_size(v), "%zu");

    vec_free(v);
    PASS();
}

TEST integration_mixed_operations(void)
{
    int *v = NULL;
    vec_init(v, int);

    vec_push_back(v, 1);
    vec_push_back(v, 2);
    vec_push_back(v, 3);
    vec_insert(v, 1, 9);
    vec_erase(v, 0);
    vec_pop_back(v);
    vec_insert(v, vec_size(v), 5);

    ASSERT_EQ_FMT((size_t)3, vec_size(v), "%zu");
    int expect[3] = {9, 2, 5};
    for (int i = 0; i < 3; i++)
        ASSERT_EQ_FMT(expect[i], v[i], "%d");

    vec_free(v);
    PASS();
}

SUITE(vector_lifecycle)
{
    RUN_TEST(init_creates_empty_vector);
    RUN_TEST(init_records_element_size);
    RUN_TEST(free_resets_pointer_to_null);
    RUN_TEST(free_twice_is_safe);
}

SUITE(vector_modifiers)
{
    RUN_TEST(push_back_appends_and_grows_size);
    RUN_TEST(capacity_never_below_size);
    RUN_TEST(pop_back_removes_last_and_keeps_prefix);
    RUN_TEST(pop_back_on_empty_is_noop);
    RUN_TEST(insert_at_front_shifts_right);
    RUN_TEST(insert_in_middle_shifts_right);
    RUN_TEST(insert_at_end_is_append);
    RUN_TEST(insert_into_empty_vector);
    RUN_TEST(insert_triggers_realloc);
    RUN_TEST(erase_front_shifts_left);
    RUN_TEST(erase_middle_shifts_left);
    RUN_TEST(erase_last_element);
    RUN_TEST(erase_out_of_bounds_is_noop);
}

SUITE(vector_sizing)
{
    RUN_TEST(clear_sets_size_to_zero);
    RUN_TEST(clear_keeps_vector_reusable);
    RUN_TEST(clear_retains_capacity);
    RUN_TEST(resize_grow_keeps_prefix_and_zeroes_tail);
    RUN_TEST(resize_shrink_updates_size_and_keeps_prefix);
    RUN_TEST(resize_to_zero_empties_vector);
    RUN_TEST(resize_regrow_after_shrink_zeroes);
}

SUITE(vector_misc)
{
    RUN_TEST(swap_exchanges_size_and_contents);
    RUN_TEST(swap_with_empty_vector);
    RUN_TEST(stores_struct_elements_by_value);
    RUN_TEST(stores_many_struct_elements);
    RUN_TEST(stress_many_push_then_pop);
    RUN_TEST(integration_mixed_operations);
}

GREATEST_MAIN_DEFS();

int main(int argc, char **argv)
{
    GREATEST_MAIN_BEGIN();
    RUN_SUITE(vector_lifecycle);
    RUN_SUITE(vector_modifiers);
    RUN_SUITE(vector_sizing);
    RUN_SUITE(vector_misc);
    GREATEST_MAIN_END();
}
